### ISSUE TITLE
add taobao.shop.get api 

### ISSUE THREAD

**Issue by christineRR** [alibaba/top#2]
需要新增taobao.shop.get 的api调用，对于top地址http://api.taobao.com/apidoc/api.htm?spm=0.0.0.37.9fb8e&path=cid:9-apiId:68

**Comment by fengmk2** [comment]
OK, I will add the api support today.

**Comment by fengmk2** [comment]
@christineRR done

**Comment by christineRR** [comment]
thanks,good job!
